version: "3.8"

services:

  localstack:
    image: localstack/localstack:stable-amd64
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - HOSTNAME_EXTERNAL=172.18.128.69
      - EAGER_SERVICE_LOADING=1
      - SERVICES=sqs,s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init:/etc/localstack/init"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

#  process-video:
#    build: .
#    container_name: process-video
#    environment:
#      - SPRING_PROFILES_ACTIVE
#      - AWS_REGION
#      - AWS_ACCESS_KEY
#      - AWS_SECRET_KEY
#      - PROCESS-VIDEO-QUEUE
#      - VIDEO-UPDATE-QUEUE
#    depends_on:
#      payment-db:
#        condition: service_healthy
#    networks:
#      - hackathon
#    ports:
#      - "8091:8091"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 128M

#networks:
#  hackathon:
#    driver: bridge