spring:
  cloud:
    aws:
      region:
        static: us-east-1
      s3:
        path-style-access-enabled: false

app:
  sqs:
    video-process-command-url: ${SQS_VIDEO_PROCESS_COMMAND_URL}
    video-updated-event-url: ${SQS_VIDEO_UPDATED_EVENT_URL}
  frame-extraction:
    thread-pool-size: ${APP_FRAME_EXTRACTION_THREAD_POOL_SIZE:2}
    queue-capacity: ${APP_FRAME_EXTRACTION_QUEUE_CAPACITY:100}
