spring:
  application:
    name: process-video
  profiles:
    active: dev
  cloud:
    aws:
      sqs:
        listener:
          max-concurrent-messages: 1  # Processa 1 por vez
          max-messages-per-poll: 1
          poll-timeout: 10
          acknowledgement-mode: MANUAL
          queue-attributes-resolution-strategy: INHERIT

app:
  s3:
    bucket-videos: video-storage-bucket
    bucket-frames: frame-storage-bucket
  buckets:
    video-input-storage: video-input-storage
    video-processed-storage: video-processed-storage
  queues:
    video-process-command: video-process-command
    video-updated-event: video-updated-event
  sqs:
    video-process-command-url: ${SQS_VIDEO_PROCESS_COMMAND_URL:http://localhost:4566/000000000000/video-process-command}
    video-updated-event-url: ${SQS_VIDEO_UPDATED_EVENT_URL:http://localhost:4566/000000000000/video-updated-event}
  frame-extraction:
    thread-pool-size: 4
    queue-capacity: 100
