apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: process-video-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: process-video-secrets
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: /process-video/aws/access-key-id

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: /process-video/aws/secret-access-key

    - secretKey: SQS_VIDEO_PROCESS_COMMAND_QUEUE_NAME
      remoteRef:
        key: /process-video/sqs/video-process-command-queue-name

    - secretKey: SQS_VIDEO_UPDATED_EVENT_QUEUE_NAME
      remoteRef:
        key: /process-video/sqs/video-updated-event-queue-name
