---
name: CI - Build, Testes, Docker e PR

on:
  push:
    branches-ignore:
      - main
      - hom
      - dev
    paths-ignore:
      - '**.md'

jobs:

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build \
            -t process-video:${{ github.sha }} \
            .